# Generated by Django 4.1.3 on 2023-06-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.CharField(max_length=250)),
                ('deta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=250)),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalprojtapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=100)),
                ('branches', models.CharField(max_length=250)),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalprojtapp.district')),
            ],
        ),
    ]
